### ISSUE TITLE
函数可以脱离进程存在吗，有哪些影响呢？

### ISSUE THREAD

**Issue by cosunny** [fff455/fe-share#3]
"web服务器的请求到达时，服务器动态地加载和链接适当的函数 然后直接调用它，而不是在子进程中的上下文中运行函数。" 摘录自<深入理解计算机系统 7.11> 当函数没有进程辅助的时候，不是栈就用不了了吗，那类似迭代的情况怎么处理呢。

**Comment by xiaobaiha** [comment]
我理解它的意思不是函数脱离了进程，函数的执行肯定是依赖在某个进程。它说的应该是动态链接吧，进程之间可以共享动态链接库，而不是在子进程中单独去链接/执行函数

**Comment by cosunny** [comment]
> 我理解它的意思不是函数脱离了进程，函数的执行肯定是依赖在某个进程。它说的应该是动态链接吧，进程之间可以共享动态链接库，而不是在子进程中单独去链接/执行函数

那倒未必 比如操作系统还没起的时候 bios就可以跑，而且简单的，不借助库的'运算'也属于函数的范畴。

**Comment by xiaobaiha** [comment]
如果前提不是操作系统的话那一切也没有意义，不是操作系统也就不会有堆栈。bios阶段内存还没有初始化，即使使用类似函数的运算，也不支持使用堆栈吧

**Comment by cosunny** [comment]
> 如果前提不是操作系统的话那一切也没有意义，不是操作系统也就不会有堆栈。bios阶段内存还没有初始化，即使使用类似函数的运算，也不支持使用堆栈吧

关于操作系统的基座你说的有道理 但我还没有了解过bios细节 所以不太确定它是如何处理函数的 回头了解下。

那回到问题本身，原文上下文是这样的： “早期的web服务器通过fork和execve创建一个子进程，并在该子进程的上下文中运行CGI生成动态内容(注:这应该和你的理解一样)。 然而现代高性能的Web服务器可以使用基于动态连接的更有效和完善的方法来生成动态内容"  

我觉得应该不是你说的意思.. 你可以先回去康康书

**Comment by xiaobaiha** [comment]
回到问题的场景中，我觉得场景中的子进程是指当前的web服务器是指一个主进程和多个worker进程的这种模式，在一个请求到来时，不是在当前worker进程重新去链接一遍函数，而是通过主进程和进程间通信来直接使用函数，我这样理解哪里有问题吗
